Models migrations
splay-project-v2/backend pull request #2
Opened 2019-01-14 07:08 UTC by srozen

Migrations created and ready, reflecting previous database state.

2019-01-15 13:58 UTC, Willfrit requested changes

2019-01-15 13:58 UTC, Willfrit commented on app/controllers/application_controller.rb
> +    JWT.encode({'id': id, 'email': email}, Rails.application.credentials.jwt_secret, 'HS256')
```suggestion
    JWT.encode({'id': id, 'user': username}, Rails.application.credentials.jwt_secret, 'HS256')
```
username as the unique key - email is optional.

2019-01-15 13:59 UTC, Willfrit approved these changes

2019-01-17 02:25 UTC, srozen commented on app/controllers/application_controller.rb
> +    JWT.encode({'id': id, 'email': email}, Rails.application.credentials.jwt_secret, 'HS256')
this will be `'username' : username`

2019-01-17 07:08 UTC, merged